server.port=8063
spring.application.name=docker-hub
spring.ai.openai.api-key=_
spring.ai.openai.chat.base-url=http://localhost:8180/
#spring.ai.openai.chat.completions-path=/v1/chat/completions 

# https://docs.spring.io/spring-ai/reference/api/chat/ollama-chat.html
spring.ai.ollama.base-url=http://localhost:8180
# spring.ai.ollama.chat.options.model=llama3
spring.ai.ollama.chat.options.model=llava
# spring.ai.ollama.chat.options.model=qwen3:0.6b
# spring.ai.ollama.chat.options.model=hf.co/bartowski/gemma-2-2b-it-GGUF
# spring.ai.ollama.chat.options.model=mistral
spring.ai.ollama.chat.options.temperature=0.7
spring.ai.ollama.init.pull-model-strategy=when-missing
spring.ai.ollama.init.timeout=10m


spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
server.tomcat.max-swallow-size=50MB